packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.1
  '@tailwindcss/postcss': ^4.1.17
  '@tanstack/react-form': ^1.26.0
  '@types/node': ^24.10.1
  eslint: ^9.39.1
  prettier: ^3.6.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  zod: 4.1.13

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.0
    react-dom: ^19.2.0

ignoredBuiltDependencies:
  - '@clerk/shared'
  - browser-tabs-lock
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - unrs-resolver
